[project]
name = "shiny-for-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gunicorn>=23.0.0",
    "shiny>=1.2.1",
]

[tool.uv.workspace]
members = ["routes_example_app", "shinylive_quarto"]
