[project]
name = "routes-example-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.8",
    "gunicorn>=23.0.0",
    "shiny>=1.2.1",
]
