name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: vancouver-blocks
  VERSION: latest
  CONTEXT: shinylive_without_quarto

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       cd $CONTEXT
       docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
